[theme]

# Primary accent for interactive elements
primaryColor = '#16a085'

# Background color for the main content area
backgroundColor = '#fff'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#1abc9c'

# Color used for almost all text
textColor = '#000'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"